=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/witchhunters-guild/job/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.swordsandsorcery.com/witchhunters-guild-job"
           xmlns="http://www.swordsandsorcery.com/witchhunters-guild-job" elementFormDefault="qualified">
    <xs:element name="witchhunters-guild-job">
        <xs:complexType>
            <xs:all>
                <xs:element name="id" type="xs:unsignedInt" minOccurs="1"/>
                <xs:element name="name" type="xs:string" minOccurs="1"/>
                <xs:element name="description" type="xs:string" minOccurs="1"/>
                <xs:element name="reward" type="xs:integer" minOccurs="1"/>
                <xs:element name="requirements" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="requirement" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="id" type="xs:unsignedInt" minOccurs="1"/>
                                        <xs:element name="amount" type="xs:unsignedInt" minOccurs="1"/>
                                    </xs:all>
                                    <xs:attribute name="type" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/witchhunters-guild/job/definition/5.xml
<?xml version="1.0" encoding="UTF-8"?>

<witchhunters-guild-job:witchhunters-guild-job xmlns:witchhunters-guild-job="http://www.swordsandsorcery.com/witchhunters-guild-job"
                                               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                               xsi:schemaLocation="http://www.swordsandsorcery.com/witchhunters-guild-job ../schema.xsd">
    <witchhunters-guild-job:id>5</witchhunters-guild-job:id>
    <witchhunters-guild-job:name>Pray a tribute.</witchhunters-guild-job:name>
    <witchhunters-guild-job:description>Quest 5 description.</witchhunters-guild-job:description>
    <witchhunters-guild-job:reward>10</witchhunters-guild-job:reward>
    <witchhunters-guild-job:requirements>
        <witchhunters-guild-job:requirement type="ITEM">
            <witchhunters-guild-job:id>50</witchhunters-guild-job:id>
            <witchhunters-guild-job:amount>1</witchhunters-guild-job:amount>
        </witchhunters-guild-job:requirement>
    </witchhunters-guild-job:requirements>
</witchhunters-guild-job:witchhunters-guild-job>
