=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/race/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.swordsandsorcery.com/race"
           xmlns="http://www.swordsandsorcery.com/race" elementFormDefault="qualified">
    <xs:element name="race">
        <xs:complexType>
            <xs:all>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="modifier-list" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="modifier" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="type">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="STRENGTH"/>
                                                    <xs:enumeration value="ENDURANCE"/>
                                                    <xs:enumeration value="VITALITY"/>
                                                    <xs:enumeration value="INTELLIGENCE"/>
                                                    <xs:enumeration value="WISDOM"/>
                                                    <xs:enumeration value="WILLPOWER"/>
                                                    <xs:enumeration value="PERCEPTION"/>
                                                    <xs:enumeration value="SWIFTNESS"/>
                                                    <xs:enumeration value="DEXTERITY"/>
                                                    <xs:enumeration value="CHARISMA"/>
                                                    <xs:enumeration value="BEAUTY"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="value" type="xs:byte"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/race/definition/elf.xml
<?xml version="1.0" encoding="UTF-8"?>

<race:race xmlns:race="http://www.swordsandsorcery.com/race" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.swordsandsorcery.com/race ../schema.xsd">
    <race:name>Elf</race:name>
    <race:modifier-list>
        <race:modifier>
            <race:type>INTELLIGENCE</race:type>
            <race:value>20</race:value>
        </race:modifier>
        <race:modifier>
            <race:type>WILLPOWER</race:type>
            <race:value>10</race:value>
        </race:modifier>
        <race:modifier>
            <race:type>BEAUTY</race:type>
            <race:value>10</race:value>
        </race:modifier>
        <race:modifier>
            <race:type>STRENGTH</race:type>
            <race:value>-20</race:value>
        </race:modifier>
        <race:modifier>
            <race:type>ENDURANCE</race:type>
            <race:value>-20</race:value>
        </race:modifier>
        <race:modifier>
            <race:type>VITALITY</race:type>
            <race:value>-10</race:value>
        </race:modifier>
    </race:modifier-list>
</race:race>
