=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/item/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.swordsandsorcery.com/item"
           xmlns="http://www.swordsandsorcery.com/item" elementFormDefault="qualified">
    <xs:element name="item">
        <xs:complexType>
            <xs:all>
                <xs:element name="id" type="xs:unsignedInt" minOccurs="1"/>
                <xs:element name="name" type="xs:string" minOccurs="1"/>
                <xs:element name="equipment" type="xs:boolean" minOccurs="0"/>
                <xs:element name="type" minOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="TWO_HANDED_CRUSHING_WEAPONS"/>
                            <xs:enumeration value="ONE_HANDED_CRUSHING_WEAPONS"/>
                            <xs:enumeration value="TWO_HANDED_AXES"/>
                            <xs:enumeration value="ONE_HANDED_AXES"/>
                            <xs:enumeration value="THROWING_WEAPONS"/>
                            <xs:enumeration value="LONGSWORDS"/>
                            <xs:enumeration value="SHORTSWORDS"/>
                            <xs:enumeration value="POLEARMS"/>
                            <xs:enumeration value="DAGGERS"/>
                            <xs:enumeration value="LONGBOWS"/>
                            <xs:enumeration value="SHORTBOWS"/>
                            <xs:enumeration value="CROSSBOWS"/>
                            <xs:enumeration value="LIGHT_ARMOR"/>
                            <xs:enumeration value="HEAVY_ARMOR"/>
                            <xs:enumeration value="ROBE_ARMOR"/>
                            <xs:enumeration value="SHIELD"/>
                            <xs:enumeration value="STAFF"/>
                            <xs:enumeration value="WAND"/>
                            <xs:enumeration value="SPECTRE"/>
                            <xs:enumeration value="COIN"/>
                            <xs:enumeration value="NUT"/>
                            <xs:enumeration value="ORE"/>
                            <xs:enumeration value="BAR"/>
                            <xs:enumeration value="ARROW"/>
                            <xs:enumeration value="MATERIAL"/>
                            <xs:enumeration value="TOOL"/>
                            <xs:enumeration value="RECIPE"/>
                            <xs:enumeration value="FRUIT"/>
                            <xs:enumeration value="FOOD"/>
                            <xs:enumeration value="SCROLL"/>
                            <xs:enumeration value="AMULET"/>
                            <xs:enumeration value="GLOVES"/>
                            <xs:enumeration value="BOOTS"/>
                            <xs:enumeration value="HELM"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="price" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="price-entry">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="type">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="MONEY"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="amount" type="xs:int" />
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="usable" type="xs:boolean" default="false" minOccurs="0"/>
                <xs:element name="use-effect-list" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="effect" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="settings-list" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="effect-setting" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:all>
                                                                <xs:element name="setting-name" type="xs:string"
                                                                            minOccurs="1"
                                                                            maxOccurs="1"/>
                                                                <xs:element name="setting-value" type="xs:string"
                                                                            minOccurs="1"
                                                                            maxOccurs="1"/>
                                                            </xs:all>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="target" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="weight" type="xs:unsignedInt" minOccurs="1"/>
                <xs:element name="modifiers" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="modifier" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="modifier" minOccurs="1" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="ATTACK"/>
                                                    <xs:enumeration value="AIMING"/>
                                                    <xs:enumeration value="DEFENSE"/>
                                                    <xs:enumeration value="SPELL_RESISTANCE"/>
                                                    <xs:enumeration value="DAMAGE"/>
                                                    <xs:enumeration value="RANGED_DAMAGE"/>
                                                    <xs:enumeration value="INITIATION"/>
                                                    <xs:enumeration value="LIFE"/>
                                                    <xs:enumeration value="MANA"/>
                                                    <xs:enumeration value="STRENGTH"/>
                                                    <xs:enumeration value="PERCEPTION"/>
                                                    <xs:enumeration value="DEXTERITY"/>
                                                    <xs:enumeration value="TWO_HANDED_CRUSHING_WEAPONS"/>
                                                    <xs:enumeration value="ONE_HANDED_CRUSHING_WEAPONS"/>
                                                    <xs:enumeration value="ONE_HANDED_AXES"/>
                                                    <xs:enumeration value="MOVEMENT"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="amount" type="xs:integer" minOccurs="1" maxOccurs="1"/>
                                        <xs:element name="d2" type="xs:unsignedInt" minOccurs="0"/>
                                        <xs:element name="d4" type="xs:unsignedInt" minOccurs="0"/>
                                        <xs:element name="d6" type="xs:unsignedInt" minOccurs="0"/>
                                        <xs:element name="d8" type="xs:unsignedInt" minOccurs="0"/>
                                        <xs:element name="d10" type="xs:unsignedInt" minOccurs="0"/>
                                        <xs:element name="d20" type="xs:unsignedInt" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="requirements" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="requirement" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="requirement" minOccurs="1" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="ATTACK"/>
                                                    <xs:enumeration value="DEFENSE"/>
                                                    <xs:enumeration value="INITIATION"/>
                                                    <xs:enumeration value="LIFE"/>
                                                    <xs:enumeration value="MOVEMENT"/>
                                                    <xs:enumeration value="TWO_HANDED_CRUSHING_WEAPONS"/>
                                                    <xs:enumeration value="ONE_HANDED_CRUSHING_WEAPONS"/>
                                                    <xs:enumeration value="ONE_HANDED_AXES"/>
                                                    <xs:enumeration value="STRENGTH"/>
                                                    <xs:enumeration value="PERCEPTION"/>
                                                    <xs:enumeration value="DEXTERITY"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="amount" type="xs:integer" minOccurs="1" maxOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/item/definition/138.xml
<?xml version="1.0" encoding="UTF-8"?>

<item:item xmlns:item="http://www.swordsandsorcery.com/item" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.swordsandsorcery.com/item ../schema.xsd">
    <item:id>9</item:id>
    <item:name>Chipped bronze axe</item:name>
    <item:type>WEAPON</item:type>
    <item:subtype>ONE_HANDED_AXES</item:subtype>
    <item:equipment>true</item:equipment>
    <item:modifiers>
        <item:modifier>
            <item:modifier>DAMAGE</item:modifier>
            <item:amount>1</item:amount>
            <item:d4>1</item:d4>
        </item:modifier>
    </item:modifiers>
    <item:weight>200</item:weight>
    <item:price>
        <item:price-entry>
            <item:type>MONEY</item:type>
            <item:amount>1</item:amount>
        </item:price-entry>
    </item:price>
</item:item>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/item/definition/135.xml
<?xml version="1.0" encoding="UTF-8"?>

<item:item xmlns:item="http://www.swordsandsorcery.com/item" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.swordsandsorcery.com/item ../schema.xsd">
    <item:id>135</item:id>
    <item:name>Worn leather tunic</item:name>
    <item:type>ARMOR</item:type>
    <item:subtype>LIGHT_ARMOR</item:subtype>
    <item:weight>400</item:weight>
    <item:equipment>true</item:equipment>
    <item:modifiers>
        <item:modifier>
            <item:modifier>DEFENSE</item:modifier>
            <item:amount>1</item:amount>>
    </item:modifiers>
    <item:price>
        <item:price-entry>
            <item:type>MONEY</item:type>
            <item:amount>1</item:amount>
        </item:price-entry>
    </item:price>
</item:item>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/item/definition/200.xml
<?xml version="1.0" encoding="UTF-8"?>

<item:item xmlns:item="http://www.swordsandsorcery.com/item" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.swordsandsorcery.com/item ../schema.xsd">
  <item:id>200</item:id>
  <item:name>Silverleaf</item:name>
  <item:type>MATERIAL</item:type>
  <item:subtype>GRIMY_HERB</item:subtype>
  <item:weight>5</item:weight>
  <item:equipment>true</item:equipment>
  <item:price>
    <item:price-entry>
      <item:type>MONEY</item:type>
      <item:amount>300</item:amount>
    </item:price-entry>
  </item:price>
</item:item>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/item/definition/190.xml
<?xml version="1.0" encoding="UTF-8"?>

<item:item xmlns:item="http://www.swordsandsorcery.com/item" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.swordsandsorcery.com/item ../schema.xsd">
    <item:id>190</item:id>
    <item:name>Vial of blood</item:name>
    <item:type>MATERIAL</item:type>
    <item:weight>20</item:weight>
    <item:usable>true</item:usable>
    <item:description>Restore 8 health points when used by a vampire character but does 3 damage when used by anyone else.</item:description>
    <item:use-effect-list>
        <item:effect target="heal_vampire">
            <item:settings-list>
                <item:effect-setting>
                    <item:setting-name>heal-amount</item:setting-name>
                    <item:setting-value>8</item:setting-value>
                </item:effect-setting>
                <item:effect-setting>
                    <item:setting-name>damage-amount</item:setting-name>
                    <item:setting-value>3</item:setting-value>
                </item:effect-setting>
            </item:settings-list>
        </item:effect>
    </item:use-effect-list>
    <item:price>
        <item:price-entry>
            <item:type>MONEY</item:type>
            <item:amount>5</item:amount>
        </item:price-entry>
    </item:price>
</item:item>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/item/definition/55.xml
<?xml version="1.0" encoding="UTF-8"?>

<item:item xmlns:item="http://www.swordsandsorcery.com/item" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.swordsandsorcery.com/item ../schema.xsd">
    <item:id>55</item:id>
    <item:name>Magical amulet</item:name>
    <item:type>AMULET</item:type>
    <item:weight>0</item:weight>
    <!--
        This is an unidentified thing, there must be 3 amulets in random, one for melee one for ranged and one for magic.
        All of them should be unidentified by default.
    -->
    <item:price>
        <item:price-entry>
            <item:type>MONEY</item:type>
            <item:amount>0</item:amount>
        </item:price-entry>
    </item:price>
</item:item>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/item/definition/61.xml
<?xml version="1.0" encoding="UTF-8"?>

<item:item xmlns:item="http://www.swordsandsorcery.com/item" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.swordsandsorcery.com/item ../schema.xsd">
    <item:id>61</item:id>
    <item:name>Apple cider</item:name>
    <item:type>LIQUID</item:type>
    <item:weight>30</item:weight>
    <item:usable>true</item:usable>
    <item:description>Restore 4 health points when used.</item:description>
    <item:use-effect-list>
        <item:effect target="restore_health">
            <item:settings-list>
                <item:effect-setting>
                    <item:setting-name>amount</item:setting-name>
                    <item:setting-value>4</item:setting-value>
                </item:effect-setting>
            </item:settings-list>
        </item:effect>
        <item:effect target="remove_item">
            <item:settings-list>
                <item:effect-setting>
                    <item:setting-name>item</item:setting-name>
                    <item:setting-value>61</item:setting-value>
                </item:effect-setting>
                <item:effect-setting>
                    <item:setting-name>amount</item:setting-name>
                    <item:setting-value>1</item:setting-value>
                </item:effect-setting>
            </item:settings-list>
        </item:effect>
        <!-- TODO: add it a buff when buffs are supported in the game -->
    </item:use-effect-list>
    <item:price>
        <item:price-entry>
            <item:type>MONEY</item:type>
            <item:amount>5</item:amount>
        </item:price-entry>
    </item:price>
</item:item>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/item/definition/10.xml
<?xml version="1.0" encoding="UTF-8"?>

<item:item xmlns:item="http://www.swordsandsorcery.com/item" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.swordsandsorcery.com/item ../schema.xsd">
    <item:id>10</item:id>
    <item:name>Bronze pickaxe</item:name>
    <item:type>ONE_HANDED_CRUSHING_WEAPONS</item:type>
    <item:equipment>true</item:equipment>
    <item:modifiers>
        <item:modifier>
            <item:modifier>DEFENSE</item:modifier>
            <item:amount>2</item:amount>
        </item:modifier>
    </item:modifiers>
    <item:weight>200</item:weight>
    <item:price>
        <item:price-entry>
            <item:type>MONEY</item:type>
            <item:amount>15</item:amount>
        </item:price-entry>
    </item:price>
</item:item>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/item/definition/113.xml
<?xml version="1.0" encoding="UTF-8"?>

<item:item xmlns:item="http://www.swordsandsorcery.com/item" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.swordsandsorcery.com/item ../schema.xsd">
    <item:id>113</item:id>
    <item:name>Scroll: Bane undead</item:name>
    <item:type>SCROLL</item:type>
    <item:weight>20</item:weight>
    <item:description>You don't know how to use this scroll (yet)!</item:description>
    <item:price>
        <item:price-entry>
            <item:type>MONEY</item:type>
            <item:amount>40</item:amount>
        </item:price-entry>
    </item:price>
</item:item>
