=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/item/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.swordsandsorcery.com/item"
           xmlns="http://www.swordsandsorcery.com/item" elementFormDefault="qualified">
    <xs:element name="item">
        <xs:complexType>
            <xs:all>
                <xs:element name="id" type="xs:unsignedInt" minOccurs="1"/>
                <xs:element name="name" type="xs:string" minOccurs="1"/>
                <xs:element name="equipment" type="xs:boolean" minOccurs="0"/>
                <xs:element name="type" minOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="TWO_HANDED_CRUSHING_WEAPONS"/>
                            <xs:enumeration value="ONE_HANDED_CRUSHING_WEAPONS"/>
                            <xs:enumeration value="TWO_HANDED_AXES"/>
                            <xs:enumeration value="ONE_HANDED_AXES"/>
                            <xs:enumeration value="THROWING_WEAPONS"/>
                            <xs:enumeration value="LONGSWORDS"/>
                            <xs:enumeration value="SHORTSWORDS"/>
                            <xs:enumeration value="POLEARMS"/>
                            <xs:enumeration value="DAGGERS"/>
                            <xs:enumeration value="LONGBOWS"/>
                            <xs:enumeration value="SHORTBOWS"/>
                            <xs:enumeration value="CROSSBOWS"/>
                            <xs:enumeration value="LIGHT_ARMOR"/>
                            <xs:enumeration value="HEAVY_ARMOR"/>
                            <xs:enumeration value="ROBE_ARMOR"/>
                            <xs:enumeration value="SHIELD"/>
                            <xs:enumeration value="STAFF"/>
                            <xs:enumeration value="WAND"/>
                            <xs:enumeration value="SPECTRE"/>
                            <xs:enumeration value="COIN"/>
                            <xs:enumeration value="NUT"/>
                            <xs:enumeration value="ORE"/>
                            <xs:enumeration value="BAR"/>
                            <xs:enumeration value="ARROW"/>
                            <xs:enumeration value="MATERIAL"/>
                            <xs:enumeration value="TOOL"/>
                            <xs:enumeration value="RECIPE"/>
                            <xs:enumeration value="FRUIT"/>
                            <xs:enumeration value="FOOD"/>
                            <xs:enumeration value="SCROLL"/>
                            <xs:enumeration value="AMULET"/>
                            <xs:enumeration value="GLOVES"/>
                            <xs:enumeration value="BOOTS"/>
                            <xs:enumeration value="HELM"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="price" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="price-entry">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="type">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="MONEY"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="amount" type="xs:int" />
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="usable" type="xs:boolean" default="false" minOccurs="0"/>
                <xs:element name="use-effect-list" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="effect" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="settings-list" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="effect-setting" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:all>
                                                                <xs:element name="setting-name" type="xs:string"
                                                                            minOccurs="1"
                                                                            maxOccurs="1"/>
                                                                <xs:element name="setting-value" type="xs:string"
                                                                            minOccurs="1"
                                                                            maxOccurs="1"/>
                                                            </xs:all>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="target" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="weight" type="xs:unsignedInt" minOccurs="1"/>
                <xs:element name="modifiers" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="modifier" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="modifier" minOccurs="1" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="ATTACK"/>
                                                    <xs:enumeration value="AIMING"/>
                                                    <xs:enumeration value="DEFENSE"/>
                                                    <xs:enumeration value="SPELL_RESISTANCE"/>
                                                    <xs:enumeration value="DAMAGE"/>
                                                    <xs:enumeration value="RANGED_DAMAGE"/>
                                                    <xs:enumeration value="INITIATION"/>
                                                    <xs:enumeration value="LIFE"/>
                                                    <xs:enumeration value="MANA"/>
                                                    <xs:enumeration value="STRENGTH"/>
                                                    <xs:enumeration value="PERCEPTION"/>
                                                    <xs:enumeration value="DEXTERITY"/>
                                                    <xs:enumeration value="TWO_HANDED_CRUSHING_WEAPONS"/>
                                                    <xs:enumeration value="ONE_HANDED_CRUSHING_WEAPONS"/>
                                                    <xs:enumeration value="ONE_HANDED_AXES"/>
                                                    <xs:enumeration value="MOVEMENT"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="amount" type="xs:integer" minOccurs="1" maxOccurs="1"/>
                                        <xs:element name="d2" type="xs:unsignedInt" minOccurs="0"/>
                                        <xs:element name="d4" type="xs:unsignedInt" minOccurs="0"/>
                                        <xs:element name="d6" type="xs:unsignedInt" minOccurs="0"/>
                                        <xs:element name="d8" type="xs:unsignedInt" minOccurs="0"/>
                                        <xs:element name="d10" type="xs:unsignedInt" minOccurs="0"/>
                                        <xs:element name="d20" type="xs:unsignedInt" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="requirements" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="requirement" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="requirement" minOccurs="1" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="ATTACK"/>
                                                    <xs:enumeration value="DEFENSE"/>
                                                    <xs:enumeration value="INITIATION"/>
                                                    <xs:enumeration value="LIFE"/>
                                                    <xs:enumeration value="MOVEMENT"/>
                                                    <xs:enumeration value="TWO_HANDED_CRUSHING_WEAPONS"/>
                                                    <xs:enumeration value="ONE_HANDED_CRUSHING_WEAPONS"/>
                                                    <xs:enumeration value="ONE_HANDED_AXES"/>
                                                    <xs:enumeration value="STRENGTH"/>
                                                    <xs:enumeration value="PERCEPTION"/>
                                                    <xs:enumeration value="DEXTERITY"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="amount" type="xs:integer" minOccurs="1" maxOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/item/definition/110.xml
<?xml version="1.0" encoding="UTF-8"?>

<item:item xmlns:item="http://www.swordsandsorcery.com/item" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.swordsandsorcery.com/item ../schema.xsd">
    <item:id>110</item:id>
    <item:name>Recipe: Bronze great axe</item:name>
    <item:type>RECIPE</item:type>
    <item:weight>1</item:weight>
    <item:usable>true</item:usable>
    <item:use-effect-list>
        <item:effect target="learn_recipe">
            <item:settings-list>
                <item:effect-setting>
                    <item:setting-name>recipe-item-id</item:setting-name>
                    <item:setting-value>110</item:setting-value>
                </item:effect-setting>
                <item:effect-setting>
                    <item:setting-name>recipe-id</item:setting-name>
                    <item:setting-value>39</item:setting-value>
                </item:effect-setting>
            </item:settings-list>
        </item:effect>
    </item:use-effect-list>
    <item:price>
        <item:price-entry>
            <item:type>MONEY</item:type>
            <item:amount>300</item:amount>
        </item:price-entry>
    </item:price>
</item:item>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/item/definition/150.xml
<?xml version="1.0" encoding="UTF-8"?>

<item:item xmlns:item="http://www.swordsandsorcery.com/item" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.swordsandsorcery.com/item ../schema.xsd">
    <item:id>150</item:id>
    <item:name>Fine robinia longbow</item:name>
    <item:type>WEAPON</item:type>
    <item:subtype>LONGBOWS</item:subtype>
    <item:weight>0</item:weight>
    <item:equipment>true</item:equipment>
    <item:modifiers>
        <item:modifier>
            <item:modifier>AIMING</item:modifier>
            <item:amount>2</item:amount>
            <item:d2>1</item:d2>
        </item:modifier>
        <item:modifier>
            <item:modifier>RANGED_DAMAGE</item:modifier>
            <item:amount>2</item:amount>
            <item:d4>1</item:d4>
        </item:modifier>
        <item:modifier>
            <item:modifier>DEFENSE</item:modifier>
            <item:amount>-2</item:amount>
        </item:modifier>
    </item:modifiers>
    <item:requirements>
        <item:requirement>
            <item:requirement>LONGBOWS</item:requirement>
            <item:amount>5</item:amount>
        </item:requirement>
    </item:requirements>
    <item:price>
        <item:price-entry>
            <item:type>MONEY</item:type>
            <item:amount>110</item:amount>
        </item:price-entry>
    </item:price>
</item:item>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/item/definition/63.xml
<?xml version="1.0" encoding="UTF-8"?>

<item:item xmlns:item="http://www.swordsandsorcery.com/item" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.swordsandsorcery.com/item ../schema.xsd">
    <item:id>63</item:id>
    <item:name>Robinia shortbow</item:name>
    <item:type>WEAPON</item:type>
    <item:subtype>SHORTBOWS</item:subtype>
    <item:weight>0</item:weight>
    <item:equipment>true</item:equipment>
    <item:modifiers>
        <item:modifier>
            <item:modifier>AIMING</item:modifier>
            <item:amount>2</item:amount>
            <item:d4>1</item:d4>
        </item:modifier>
    </item:modifiers>
    <item:requirements>
        <item:requirement>
            <item:requirement>SHORTBOWS</item:requirement>
            <item:amount>1</item:amount>
        </item:requirement>
    </item:requirements>
    <item:price>
        <item:price-entry>
            <item:type>MONEY</item:type>
            <item:amount>20</item:amount>
        </item:price-entry>
    </item:price>
</item:item>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/item/definition/14.xml
<?xml version="1.0" encoding="UTF-8"?>

<item:item xmlns:item="http://www.swordsandsorcery.com/item" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.swordsandsorcery.com/item ../schema.xsd">
    <item:id>14</item:id>
    <item:name>Apple</item:name>
    <item:type>FRUIT</item:type>
    <item:weight>10</item:weight>
    <item:usable>true</item:usable>
    <item:use-effect-list>
        <item:effect target="com.morethanheroic.swords.combat.domain.effect.entry.HealCombatEffectDefinition">
          	<item:settings-list>
              	<item:effect-setting>
                  	<item:setting-name>amount</item:setting-name>
                  	<item:setting-value>5</item:setting-value>
                </item:effect-setting>
            </item:settings-list>
      	</item:effect>
        <item:effect target="com.morethanheroic.swords.combat.domain.effect.entry.RemoveItemAmountEffectDefinition">
            <item:settings-list>
                <item:effect-setting>
                    <item:setting-name>item</item:setting-name>
                    <item:setting-value>14</item:setting-value>
                </item:effect-setting>
                <item:effect-setting>
                    <item:setting-name>amount</item:setting-name>
                    <item:setting-value>1</item:setting-value>
                </item:effect-setting>
            </item:settings-list>
        </item:effect>
    </item:use-effect-list>
    <item:price>
        <item:price-entry>
            <item:type>MONEY</item:type>
            <item:amount>3</item:amount>
        </item:price-entry>
    </item:price>
</item:item>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/item/definition/163.xml
<?xml version="1.0" encoding="UTF-8"?>

<item:item xmlns:item="http://www.swordsandsorcery.com/item" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.swordsandsorcery.com/item ../schema.xsd">
    <item:id>163</item:id>
    <item:rarity>RARE</item:rarity>
    <item:name>Belt of Scavenging</item:name>
    <item:type>ARMOR</item:type>
    <item:subtype>BELT</item:subtype>
    <item:weight>1000</item:weight>
    <item:equipment>true</item:equipment>
    <item:modifiers>
        <item:modifier>
            <item:modifier>SCAVENGING_BONUS</item:modifier>
            <item:amount>20</item:amount>
        </item:modifier>
    </item:modifiers>
    <item:price>
        <item:price-entry>
            <item:type>MONEY</item:type>
            <item:amount>2000</item:amount>
        </item:price-entry>
    </item:price>
</item:item>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/item/definition/198.xml
<?xml version="1.0" encoding="UTF-8"?>

<item:item xmlns:item="http://www.swordsandsorcery.com/item" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.swordsandsorcery.com/item ../schema.xsd">
    <item:id>198</item:id>
    <item:name>Silver arrow</item:name>
    <item:type>PROJECTILE</item:type>
    <item:subtype>ARROW</item:subtype>
    <item:weight>5</item:weight>
    <item:equipment>true</item:equipment>
    <item:tradeable>false</item:tradeable>
    <item:modifiers>
        <item:modifier>
            <item:modifier>EXTRA_DAMAGE_AGAINST_VAMPIRES</item:modifier>
            <item:amount>3</item:amount>
        </item:modifier>
    </item:modifiers>
    <item:price>
        <item:price-entry>
            <item:type>MONEY</item:type>
            <item:amount>10</item:amount>
        </item:price-entry>
    </item:price>
</item:item>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/item/definition/111.xml
<?xml version="1.0" encoding="UTF-8"?>

<item:item xmlns:item="http://www.swordsandsorcery.com/item" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.swordsandsorcery.com/item ../schema.xsd">
    <item:id>111</item:id>
    <item:name>Lockpick</item:name>
    <item:type>TOOL</item:type>
    <item:weight>3</item:weight>
    <item:description>Used to pick locks on doors and chests. Required by the lockpicking skill.</item:description>
    <item:price>
        <item:price-entry>
            <item:type>MONEY</item:type>
            <item:amount>60</item:amount>
        </item:price-entry>
    </item:price>
</item:item>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/item/definition/41.xml
<?xml version="1.0" encoding="UTF-8"?>

<item:item xmlns:item="http://www.swordsandsorcery.com/item" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.swordsandsorcery.com/item ../schema.xsd">
    <item:id>41</item:id>
    <item:name>Bronze gauntlets</item:name>
    <item:type>GLOVES</item:type>
    <item:weight>200</item:weight>
    <item:equipment>true</item:equipment>
    <item:modifiers>
        <item:modifier>
            <item:modifier>DEFENSE</item:modifier>
            <item:amount>1</item:amount>
        </item:modifier>
    </item:modifiers>
    <item:price>
        <item:price-entry>
            <item:type>MONEY</item:type>
            <item:amount>30</item:amount>
        </item:price-entry>
    </item:price>
</item:item>
