=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/item/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.swordsandsorcery.com/item"
           xmlns="http://www.swordsandsorcery.com/item" elementFormDefault="qualified">
    <xs:element name="item">
        <xs:complexType>
            <xs:all>
                <xs:element name="id" type="xs:unsignedInt" minOccurs="1"/>
                <xs:element name="name" type="xs:string" minOccurs="1"/>
                <xs:element name="equipment" type="xs:boolean" minOccurs="0"/>
                <xs:element name="type" minOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="TWO_HANDED_CRUSHING_WEAPONS"/>
                            <xs:enumeration value="ONE_HANDED_CRUSHING_WEAPONS"/>
                            <xs:enumeration value="TWO_HANDED_AXES"/>
                            <xs:enumeration value="ONE_HANDED_AXES"/>
                            <xs:enumeration value="THROWING_WEAPONS"/>
                            <xs:enumeration value="LONGSWORDS"/>
                            <xs:enumeration value="SHORTSWORDS"/>
                            <xs:enumeration value="POLEARMS"/>
                            <xs:enumeration value="DAGGERS"/>
                            <xs:enumeration value="LONGBOWS"/>
                            <xs:enumeration value="SHORTBOWS"/>
                            <xs:enumeration value="CROSSBOWS"/>
                            <xs:enumeration value="LIGHT_ARMOR"/>
                            <xs:enumeration value="HEAVY_ARMOR"/>
                            <xs:enumeration value="ROBE_ARMOR"/>
                            <xs:enumeration value="SHIELD"/>
                            <xs:enumeration value="STAFF"/>
                            <xs:enumeration value="WAND"/>
                            <xs:enumeration value="SPECTRE"/>
                            <xs:enumeration value="COIN"/>
                            <xs:enumeration value="NUT"/>
                            <xs:enumeration value="ORE"/>
                            <xs:enumeration value="BAR"/>
                            <xs:enumeration value="ARROW"/>
                            <xs:enumeration value="MATERIAL"/>
                            <xs:enumeration value="TOOL"/>
                            <xs:enumeration value="RECIPE"/>
                            <xs:enumeration value="FRUIT"/>
                            <xs:enumeration value="FOOD"/>
                            <xs:enumeration value="SCROLL"/>
                            <xs:enumeration value="AMULET"/>
                            <xs:enumeration value="GLOVES"/>
                            <xs:enumeration value="BOOTS"/>
                            <xs:enumeration value="HELM"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="price" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="price-entry">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="type">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="MONEY"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="amount" type="xs:int" />
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="usable" type="xs:boolean" default="false" minOccurs="0"/>
                <xs:element name="use-effect-list" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="effect" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="settings-list" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="effect-setting" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:all>
                                                                <xs:element name="setting-name" type="xs:string"
                                                                            minOccurs="1"
                                                                            maxOccurs="1"/>
                                                                <xs:element name="setting-value" type="xs:string"
                                                                            minOccurs="1"
                                                                            maxOccurs="1"/>
                                                            </xs:all>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="target" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="weight" type="xs:unsignedInt" minOccurs="1"/>
                <xs:element name="modifiers" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="modifier" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="modifier" minOccurs="1" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="ATTACK"/>
                                                    <xs:enumeration value="AIMING"/>
                                                    <xs:enumeration value="DEFENSE"/>
                                                    <xs:enumeration value="SPELL_RESISTANCE"/>
                                                    <xs:enumeration value="DAMAGE"/>
                                                    <xs:enumeration value="RANGED_DAMAGE"/>
                                                    <xs:enumeration value="INITIATION"/>
                                                    <xs:enumeration value="LIFE"/>
                                                    <xs:enumeration value="MANA"/>
                                                    <xs:enumeration value="STRENGTH"/>
                                                    <xs:enumeration value="PERCEPTION"/>
                                                    <xs:enumeration value="DEXTERITY"/>
                                                    <xs:enumeration value="TWO_HANDED_CRUSHING_WEAPONS"/>
                                                    <xs:enumeration value="ONE_HANDED_CRUSHING_WEAPONS"/>
                                                    <xs:enumeration value="ONE_HANDED_AXES"/>
                                                    <xs:enumeration value="MOVEMENT"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="amount" type="xs:integer" minOccurs="1" maxOccurs="1"/>
                                        <xs:element name="d2" type="xs:unsignedInt" minOccurs="0"/>
                                        <xs:element name="d4" type="xs:unsignedInt" minOccurs="0"/>
                                        <xs:element name="d6" type="xs:unsignedInt" minOccurs="0"/>
                                        <xs:element name="d8" type="xs:unsignedInt" minOccurs="0"/>
                                        <xs:element name="d10" type="xs:unsignedInt" minOccurs="0"/>
                                        <xs:element name="d20" type="xs:unsignedInt" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="requirements" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="requirement" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="requirement" minOccurs="1" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="ATTACK"/>
                                                    <xs:enumeration value="DEFENSE"/>
                                                    <xs:enumeration value="INITIATION"/>
                                                    <xs:enumeration value="LIFE"/>
                                                    <xs:enumeration value="MOVEMENT"/>
                                                    <xs:enumeration value="TWO_HANDED_CRUSHING_WEAPONS"/>
                                                    <xs:enumeration value="ONE_HANDED_CRUSHING_WEAPONS"/>
                                                    <xs:enumeration value="ONE_HANDED_AXES"/>
                                                    <xs:enumeration value="STRENGTH"/>
                                                    <xs:enumeration value="PERCEPTION"/>
                                                    <xs:enumeration value="DEXTERITY"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="amount" type="xs:integer" minOccurs="1" maxOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/item/definition/105.xml
<?xml version="1.0" encoding="UTF-8"?>

<item:item xmlns:item="http://www.swordsandsorcery.com/item" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.swordsandsorcery.com/item ../schema.xsd">
    <item:id>105</item:id>
    <item:rarity>COMMON</item:rarity>
    <item:name>Bronze flail</item:name>
    <item:type>WEAPON</item:type>
    <item:subtype>TWO_HANDED_CRUSHING_WEAPONS</item:subtype>
    <item:weight>600</item:weight>
    <item:equipment>true</item:equipment>
    <item:modifiers>
        <item:modifier>
            <item:modifier>ATTACK</item:modifier>
            <item:amount>1</item:amount>
            <item:d2>1</item:d2>
        </item:modifier>
        <item:modifier>
            <item:modifier>DAMAGE</item:modifier>
            <item:amount>2</item:amount>
            <item:d6>1</item:d6>
        </item:modifier>
    </item:modifiers>
    <item:requirements>
        <item:requirement>
            <item:requirement>TWO_HANDED_CRUSHING_WEAPONS</item:requirement>
            <item:amount>1</item:amount>
        </item:requirement>
    </item:requirements>
    <item:price>
        <item:price-entry>
            <item:type>MONEY</item:type>
            <item:amount>50</item:amount>
        </item:price-entry>
    </item:price>
</item:item>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/item/definition/212.xml
<?xml version="1.0" encoding="UTF-8"?>

<item:item xmlns:item="http://www.swordsandsorcery.com/item" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.swordsandsorcery.com/item ../schema.xsd">
    <item:id>212</item:id>
    <item:name>Bloodstone</item:name>
    <item:type>MATERIAL</item:type>
    <item:subtype>GEM</item:subtype>
    <item:weight>5</item:weight>
    <item:price>
        <item:price-entry>
            <item:type>MONEY</item:type>
            <item:amount>1000</item:amount>
        </item:price-entry>
    </item:price>
</item:item>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/item/definition/33.xml
<?xml version="1.0" encoding="UTF-8"?>

<item:item xmlns:item="http://www.swordsandsorcery.com/item" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.swordsandsorcery.com/item ../schema.xsd">
    <item:id>33</item:id>
    <item:name>Scroll: Heal</item:name>
    <item:type>SCROLL</item:type>
    <item:weight>20</item:weight>
    <item:usable>true</item:usable>
    <item:use-effect-list>
        <item:effect target="com.morethanheroic.swords.combat.domain.effect.entry.LearnSpellEffectDefinition">
            <item:settings-list>
                <item:effect-setting>
                    <item:setting-name>spell-item-id</item:setting-name>
                    <item:setting-value>33</item:setting-value>
                </item:effect-setting>
                <item:effect-setting>
                    <item:setting-name>spell-id</item:setting-name>
                    <item:setting-value>1</item:setting-value>
                </item:effect-setting>
            </item:settings-list>
        </item:effect>
    </item:use-effect-list>
    <item:price>
        <item:price-entry>
            <item:type>MONEY</item:type>
            <item:amount>30</item:amount>
        </item:price-entry>
    </item:price>
</item:item>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/item/definition/192.xml
<?xml version="1.0" encoding="UTF-8"?>

<item:item xmlns:item="http://www.swordsandsorcery.com/item" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.swordsandsorcery.com/item ../schema.xsd">
    <item:id>192</item:id>
    <item:rarity>COMMON</item:rarity>
    <item:name>King's blood</item:name>
    <item:type>MATERIAL</item:type>
    <item:subtype>HERB</item:subtype>
    <item:weight>1</item:weight>
    <item:price>
        <item:price-entry>
            <item:type>MONEY</item:type>
            <item:amount>10</item:amount>
        </item:price-entry>
    </item:price>
</item:item>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/item/definition/247.xml
<?xml version="1.0" encoding="UTF-8"?>

<item:item xmlns:item="http://www.swordsandsorcery.com/item" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.swordsandsorcery.com/item ../schema.xsd">
    <item:id>247</item:id>
    <item:rarity>COMMON</item:rarity>
    <item:name>Avalon Robe</item:name>
    <item:type>ARMOR</item:type>
    <item:subtype>ROBE_ARMOR</item:subtype>
    <item:weight>400</item:weight>
    <item:equipment>true</item:equipment>
    <item:modifiers>
        <item:modifier>
            <item:modifier>DEFENSE</item:modifier>
            <item:amount>6</item:amount>
        </item:modifier>
        <item:modifier>
            <item:modifier>MAGIC_ATTACK</item:modifier>
            <item:amount>6</item:amount>
        </item:modifier>
        <item:modifier>
            <item:modifier>MANA</item:modifier>
            <item:amount>15</item:amount>
        </item:modifier>
    </item:modifiers>
    <item:requirements>
        <item:requirement>
            <item:requirement>ROBE_ARMOR</item:requirement>
            <item:amount>17</item:amount>
        </item:requirement>
    </item:requirements>
    <item:price>
        <item:price-entry>
            <item:type>MONEY</item:type>
            <item:amount>350</item:amount>
        </item:price-entry>
    </item:price>
</item:item>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/item/definition/18.xml
<?xml version="1.0" encoding="UTF-8"?>

<item:item xmlns:item="http://www.swordsandsorcery.com/item" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.swordsandsorcery.com/item ../schema.xsd">
    <item:id>18</item:id>
    <item:rarity>COMMON</item:rarity>
    <item:name>Vial</item:name>
    <item:type>MATERIAL</item:type>
    <item:weight>20</item:weight>
    <item:usable>true</item:usable>
    <item:use-effect-list>
        <item:effect target="fill_vials"/>
    </item:use-effect-list>
    <item:description>You can fill a maximum of five of these for 1 movement point.</item:description>
    <item:price>
        <item:price-entry>
            <item:type>MONEY</item:type>
            <item:amount>3</item:amount>
        </item:price-entry>
    </item:price>
</item:item>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/item/definition/95.xml
<?xml version="1.0" encoding="UTF-8"?>

<item:item xmlns:item="http://www.swordsandsorcery.com/item" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.swordsandsorcery.com/item ../schema.xsd">
    <item:id>95</item:id>
    <item:rarity>COMMON</item:rarity>
    <item:name>Robinia wand</item:name>
    <item:type>WEAPON</item:type>
    <item:subtype>WAND</item:subtype>
    <item:weight>200</item:weight>
    <item:equipment>true</item:equipment>
    <item:modifiers>
        <item:modifier>
            <item:modifier>MAGIC_ATTACK</item:modifier>
            <item:amount>2</item:amount>
            <item:d4>1</item:d4>
        </item:modifier>
    </item:modifiers>
    <item:requirements>
        <item:requirement>
            <item:requirement>WAND</item:requirement>
            <item:amount>1</item:amount>
        </item:requirement>
    </item:requirements>
    <item:price>
        <item:price-entry>
            <item:type>MONEY</item:type>
            <item:amount>30</item:amount>
        </item:price-entry>
    </item:price>
</item:item>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/item/definition/201.xml
<?xml version="1.0" encoding="UTF-8"?>

<item:item xmlns:item="http://www.swordsandsorcery.com/item" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.swordsandsorcery.com/item ../schema.xsd">
    <item:id>201</item:id>
    <item:rarity>UNCOMMON</item:rarity>
    <item:name>Cure for the Thirsty</item:name>
    <item:type>POTION</item:type>
    <item:tradeable>false</item:tradeable>
    <item:usable>true</item:usable>
    <item:use-effect-list>
        <item:effect target="cure_vampirism"/>
        <item:effect target="remove_item">
            <item:settings-list>
                <item:effect-setting>
                    <item:setting-name>item</item:setting-name>
                    <item:setting-value>201</item:setting-value>
                </item:effect-setting>
                <item:effect-setting>
                    <item:setting-name>amount</item:setting-name>
                    <item:setting-value>1</item:setting-value>
                </item:effect-setting>
            </item:settings-list>
        </item:effect>
    </item:use-effect-list>
    <item:description>This potion will cleanse you from the course of vampirism.</item:description>
    <item:weight>3</item:weight>
    <item:price>
        <item:price-entry>
            <item:type>MONEY</item:type>
            <item:amount>1000</item:amount>
        </item:price-entry>
    </item:price>
</item:item>
