=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/zone/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.swordsandsorcery.com/zone"
           xmlns="http://www.swordsandsorcery.com/zone" elementFormDefault="qualified">
    <xs:element name="zone">
        <xs:complexType>
            <xs:all>
                <xs:element name="id" type="xs:string"/>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="location">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="SEVGARD"/>
                            <xs:enumeration value="ILLYRIA"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="enabled" type="xs:boolean"/>
                <xs:element name="description" type="xs:string"/>
                <xs:element name="minimum-level" type="xs:integer"/>
                <xs:element name="maximum-level" type="xs:integer"/>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/zone/definition/woodland-cemetery.xml
<?xml version="1.0" encoding="UTF-8"?>

<zone:zone xmlns:zone="http://www.swordsandsorcery.com/zone" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.swordsandsorcery.com/zone ../schema.xsd">
    <zone:id>WOODLAND_CEMETERY</zone:id>
    <zone:name>Woodland cemetery</zone:name>
    <zone:enabled>true</zone:enabled>
    <zone:location>SEVGARD</zone:location>
    <zone:description>
        <![CDATA[
Beyond Sevgard’s mighty walls, in the darkest corners of the Whispering Woods lies the fabled place of undeath – known amongst the locals as the Woodland Cemetery. Story goes that it was once a peaceful cemetery, which became cursed due to, many believed, spirits who became angry due to all the grave looting. Many scholars believe that the same dark force that tainted the hearts of denizens of Whispering Woods also cursed the cemetery. Cemetery is ancient, and existed long before Sevgard was built! Stories of whose ancestors rest there are unknown. Cemetery was located by accident, by several adventurers who tried to track down a “strange, fanged creature with immeasurable thirst for blood” which terrorized farmlands. But only one adventurer came back from their quest – he started telling tales of angry spirits, horrid creatures that praised the moon, living in isolation in a city not far away from the cemetery.

Not much has passed and the curse of undeath started to affect the survivor – his skin became pale, he started hating the sunlight. Citizens of Sevgard, out of fear and ignorance, denied to help their once beloved adventurer, and chose to banish him instead. Kazir was his name – Kazir the Cursed. Once he left, people started to vanish as well, never to be seen again, and people believed that it was vengeance of Kazir.

Kazir, though, wasn’t vengeful. He left the clues all over the Whispering Woods, hoping that someone will join him in his cause of investigating the cemetery and its culture further. He was an adventurer. He still is, even in this undead form. Now accepted in the society of beasts of night, pale ones and moon howlers alike, he does his research, hoping that one day he might unite the ferocious creatures of the night, with other races of the world. He leaves whispers of adventures, seeking trailblazers, ones who would help him in his quest to investigate the ancient area. And many adventurers, hearing stories at the inns, answer the call, racing to find treasures and secrets that the ancient Cemetery, and the vast city it hides, has in store for them.
        ]]>
    </zone:description>
    <zone:minimum-level>11</zone:minimum-level>
    <zone:maximum-level>15</zone:maximum-level>
</zone:zone>
