=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/monster/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.swordsandsorcery.com/monster"
           xmlns="http://www.swordsandsorcery.com/monster" elementFormDefault="qualified">
    <xs:element name="monster">
        <xs:complexType>
            <xs:all>
                <xs:element name="id" type="xs:unsignedInt" minOccurs="1"/>
                <xs:element name="name" type="xs:string" minOccurs="1"/>
                <xs:element name="health" type="xs:unsignedInt" minOccurs="1"/>
                <xs:element name="mana" type="xs:unsignedInt" minOccurs="1"/>
                <xs:element name="level" type="xs:unsignedInt" minOccurs="1"/>
                <xs:element name="defense" type="xs:unsignedInt" minOccurs="1"/>
                <xs:element name="spell-resistance" type="xs:unsignedInt" minOccurs="1"/>
                <xs:element name="initiation" minOccurs="1">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="value" type="xs:unsignedInt" minOccurs="1"/>
                            <xs:element name="d2" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d4" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d6" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d8" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d10" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d20" type="xs:unsignedInt" minOccurs="0"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="attack" minOccurs="1">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="value" type="xs:unsignedInt" minOccurs="1"/>
                            <xs:element name="d2" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d4" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d6" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d8" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d10" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d20" type="xs:unsignedInt" minOccurs="0"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="damage" minOccurs="1">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="value" type="xs:unsignedInt" minOccurs="1"/>
                            <xs:element name="d2" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d4" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d6" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d8" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d10" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d20" type="xs:unsignedInt" minOccurs="0"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="aiming" minOccurs="1">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="value" type="xs:unsignedInt" minOccurs="1"/>
                            <xs:element name="d2" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d4" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d6" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d8" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d10" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d20" type="xs:unsignedInt" minOccurs="0"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ranged-damage" minOccurs="1">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="value" type="xs:unsignedInt" minOccurs="1"/>
                            <xs:element name="d2" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d4" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d6" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d8" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d10" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d20" type="xs:unsignedInt" minOccurs="0"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="magic-damage" minOccurs="1">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="value" type="xs:unsignedInt" minOccurs="1"/>
                            <xs:element name="d2" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d4" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d6" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d8" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d10" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d20" type="xs:unsignedInt" minOccurs="0"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="magic-attack" minOccurs="1">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="value" type="xs:unsignedInt" minOccurs="1"/>
                            <xs:element name="d2" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d4" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d6" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d8" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d10" type="xs:unsignedInt" minOccurs="0"/>
                            <xs:element name="d20" type="xs:unsignedInt" minOccurs="0"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="attack-type" minOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="MELEE"/>
                            <xs:enumeration value="RANGED"/>
                            <xs:enumeration value="MAGIC"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="droplist" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="drop" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="item" type="xs:unsignedInt" minOccurs="1"/>
                                        <xs:element name="amount" minOccurs="1">
                                            <xs:complexType>
                                                <xs:all>
                                                    <xs:element name="min" type="xs:unsignedInt" minOccurs="0"/>
                                                    <xs:element name="max" type="xs:unsignedInt" minOccurs="1"/>
                                                </xs:all>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="chance" type="xs:double" minOccurs="1"/>
                                        <xs:element name="identified" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="scavengelist" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="drop" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="item" type="xs:unsignedInt" minOccurs="1"/>
                                        <xs:element name="amount" minOccurs="1">
                                            <xs:complexType>
                                                <xs:all>
                                                    <xs:element name="min" type="xs:unsignedInt" minOccurs="0"/>
                                                    <xs:element name="max" type="xs:unsignedInt" minOccurs="1"/>
                                                </xs:all>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="chance" type="xs:double" minOccurs="1"/>
                                        <xs:element name="identified" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/monster/definition/35.xml
<?xml version="1.0" encoding="UTF-8"?>

<monster:monster xmlns:monster="http://www.swordsandsorcery.com/monster"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://www.swordsandsorcery.com/monster ../schema.xsd">
    <monster:id>35</monster:id>
    <monster:name>Skeleton Brute</monster:name>
    <monster:type>UNDEAD</monster:type>
    <monster:subtype>SKELETON</monster:subtype>
    <monster:health>45</monster:health>
    <monster:mana>0</monster:mana>
    <monster:initiation>
        <monster:value>24</monster:value>
    </monster:initiation>
    <monster:level>17</monster:level>
    <monster:defense>26</monster:defense>
    <monster:damage>
        <monster:value>2</monster:value>
        <monster:d6>1</monster:d6>
    </monster:damage>
    <monster:attack>
        <monster:value>24</monster:value>
        <monster:d4>1</monster:d4>
        <monster:d6>3</monster:d6>
    </monster:attack>
    <monster:aiming>
        <monster:value>0</monster:value>
    </monster:aiming>
    <monster:ranged-damage>
        <monster:value>0</monster:value>
    </monster:ranged-damage>
    <monster:magic-attack>
        <monster:value>0</monster:value>
    </monster:magic-attack>
    <monster:magic-damage>
        <monster:value>0</monster:value>
    </monster:magic-damage>
    <monster:spell-resistance>22</monster:spell-resistance>
    <monster:attack-type>MELEE</monster:attack-type>
    <!-- TODO: Drops! -->
</monster:monster>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/monster/definition/11.xml
<?xml version="1.0" encoding="UTF-8"?>

<monster:monster xmlns:monster="http://www.swordsandsorcery.com/monster"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://www.swordsandsorcery.com/monster ../schema.xsd">
    <monster:id>11</monster:id>
    <monster:name>Gnoll</monster:name>
    <monster:health>22</monster:health>
    <monster:mana>0</monster:mana>
    <monster:initiation>
        <monster:value>22</monster:value>
    </monster:initiation>
    <monster:level>9</monster:level>
    <monster:defense>21</monster:defense>
    <monster:damage>
        <monster:value>2</monster:value>
        <monster:d6>1</monster:d6>
    </monster:damage>
    <monster:attack>
        <monster:value>24</monster:value>
        <monster:d6>1</monster:d6>
    </monster:attack>
    <monster:aiming>
        <monster:value>0</monster:value>
    </monster:aiming>
    <monster:ranged-damage>
        <monster:value>0</monster:value>
    </monster:ranged-damage>
    <monster:magic-attack>
        <monster:value>0</monster:value>
    </monster:magic-attack>
    <monster:magic-damage>
        <monster:value>0</monster:value>
    </monster:magic-damage>
    <monster:spell-resistance>0</monster:spell-resistance>
    <monster:attack-type>MELEE</monster:attack-type>
    <monster:droplist>
        <monster:drop>
            <monster:item>111</monster:item>
            <monster:amount>
                <monster:max>1</monster:max>
            </monster:amount>
            <monster:chance>4</monster:chance>
        </monster:drop>
        <monster:drop>
            <monster:item>101</monster:item>
            <monster:amount>
                <monster:max>1</monster:max>
            </monster:amount>
            <monster:chance>0.4</monster:chance>
        </monster:drop>
        <monster:drop>
            <monster:item>103</monster:item>
            <monster:amount>
                <monster:max>1</monster:max>
            </monster:amount>
            <monster:chance>0.4</monster:chance>
        </monster:drop>
        <monster:drop>
            <monster:item>105</monster:item>
            <monster:amount>
                <monster:max>1</monster:max>
            </monster:amount>
            <monster:chance>0.4</monster:chance>
        </monster:drop>
        <monster:drop>
            <monster:item>107</monster:item>
            <monster:amount>
                <monster:max>1</monster:max>
            </monster:amount>
            <monster:chance>0.4</monster:chance>
        </monster:drop>
        <monster:drop>
            <monster:item>109</monster:item>
            <monster:amount>
                <monster:max>1</monster:max>
            </monster:amount>
            <monster:chance>0.4</monster:chance>
        </monster:drop>
        <monster:drop>
            <monster:item>100</monster:item>
            <monster:amount>
                <monster:max>1</monster:max>
            </monster:amount>
            <monster:chance>0.1</monster:chance>
        </monster:drop>
        <monster:drop>
            <monster:item>102</monster:item>
            <monster:amount>
                <monster:max>1</monster:max>
            </monster:amount>
            <monster:chance>0.2</monster:chance>
        </monster:drop>
        <monster:drop>
            <monster:item>104</monster:item>
            <monster:amount>
                <monster:max>1</monster:max>
            </monster:amount>
            <monster:chance>0.2</monster:chance>
        </monster:drop>
        <monster:drop>
            <monster:item>106</monster:item>
            <monster:amount>
                <monster:max>1</monster:max>
            </monster:amount>
            <monster:chance>0.2</monster:chance>
        </monster:drop>
        <monster:drop>
            <monster:item>108</monster:item>
            <monster:amount>
                <monster:max>1</monster:max>
            </monster:amount>
            <monster:chance>0.2</monster:chance>
        </monster:drop>
        <monster:drop>
            <monster:item>110</monster:item>
            <monster:amount>
                <monster:max>1</monster:max>
            </monster:amount>
            <monster:chance>0.2</monster:chance>
        </monster:drop>
        <monster:drop>
            <monster:item>1</monster:item>
            <monster:amount>
                <monster:min>10</monster:min>
                <monster:max>30</monster:max>
            </monster:amount>
            <monster:chance>40</monster:chance>
        </monster:drop>
        <monster:drop>
            <monster:item>99</monster:item>
            <monster:amount>
                <monster:max>1</monster:max>
            </monster:amount>
            <monster:chance>0.05</monster:chance>
        </monster:drop>
        <monster:drop>
            <monster:item>84</monster:item>
            <monster:amount>
                <monster:max>1</monster:max>
            </monster:amount>
            <monster:chance>1</monster:chance>
        </monster:drop>
        <monster:drop>
            <monster:item>77</monster:item>
            <monster:amount>
                <monster:max>1</monster:max>
            </monster:amount>
            <monster:chance>1</monster:chance>
        </monster:drop>
        <monster:drop>
            <monster:item>75</monster:item>
            <monster:amount>
                <monster:max>1</monster:max>
            </monster:amount>
            <monster:chance>2</monster:chance>
        </monster:drop>
        <monster:drop>
            <monster:item>72</monster:item>
            <monster:amount>
                <monster:max>1</monster:max>
            </monster:amount>
            <monster:chance>2</monster:chance>
        </monster:drop>
        <monster:drop>
            <monster:item>12</monster:item>
            <monster:amount>
                <monster:max>1</monster:max>
            </monster:amount>
            <monster:chance>1</monster:chance>
        </monster:drop>
    </monster:droplist>
    <monster:scavengelist>
        <monster:drop>
            <monster:item>100</monster:item>
            <monster:amount>
                <monster:max>1</monster:max>
            </monster:amount>
            <monster:chance>0.1</monster:chance>
        </monster:drop>
        <monster:drop>
            <monster:item>102</monster:item>
            <monster:amount>
                <monster:max>1</monster:max>
            </monster:amount>
            <monster:chance>0.2</monster:chance>
        </monster:drop>
        <monster:drop>
            <monster:item>104</monster:item>
            <monster:amount>
                <monster:max>1</monster:max>
            </monster:amount>
            <monster:chance>0.2</monster:chance>
        </monster:drop>
        <monster:drop>
            <monster:item>106</monster:item>
            <monster:amount>
                <monster:max>1</monster:max>
            </monster:amount>
            <monster:chance>0.2</monster:chance>
        </monster:drop>
        <monster:drop>
            <monster:item>108</monster:item>
            <monster:amount>
                <monster:max>1</monster:max>
            </monster:amount>
            <monster:chance>0.2</monster:chance>
        </monster:drop>
        <monster:drop>
            <monster:item>110</monster:item>
            <monster:amount>
                <monster:max>1</monster:max>
            </monster:amount>
            <monster:chance>0.2</monster:chance>
        </monster:drop>
        <monster:drop>
            <monster:item>99</monster:item>
            <monster:amount>
                <monster:max>1</monster:max>
            </monster:amount>
            <monster:chance>0.1</monster:chance>
        </monster:drop>
        <monster:drop>
            <monster:item>84</monster:item>
            <monster:amount>
                <monster:max>1</monster:max>
            </monster:amount>
            <monster:chance>1</monster:chance>
        </monster:drop>
        <monster:drop>
            <monster:item>77</monster:item>
            <monster:amount>
                <monster:max>1</monster:max>
            </monster:amount>
            <monster:chance>1</monster:chance>
        </monster:drop>
        <monster:drop>
            <monster:item>75</monster:item>
            <monster:amount>
                <monster:max>1</monster:max>
            </monster:amount>
            <monster:chance>2</monster:chance>
        </monster:drop>
        <monster:drop>
            <monster:item>72</monster:item>
            <monster:amount>
                <monster:max>1</monster:max>
            </monster:amount>
            <monster:chance>2</monster:chance>
        </monster:drop>
        <monster:drop>
            <monster:item>12</monster:item>
            <monster:amount>
                <monster:max>1</monster:max>
            </monster:amount>
            <monster:chance>2</monster:chance>
        </monster:drop>
    </monster:scavengelist>
</monster:monster>
