=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/spell/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.swordsandsorcery.com/spell"
           xmlns="http://www.swordsandsorcery.com/spell" elementFormDefault="qualified">
    <xs:element name="spell">
        <xs:complexType>
            <xs:all>
                <xs:element name="id" type="xs:unsignedInt" minOccurs="1"/>
                <xs:element name="name" type="xs:string" minOccurs="1"/>
                <xs:element name="combat-spell" type="xs:boolean" minOccurs="1"/>
                <xs:element name="open-page" type="xs:boolean" minOccurs="0"/>
                <xs:element name="type" minOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="DESTRUCTION"/>
                            <xs:enumeration value="ALTERATION"/>
                            <xs:enumeration value="DIVINE"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="cost-list" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cost" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="cost-type" minOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="ITEM"/>
                                                    <xs:enumeration value="MANA"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="cost-id" type="xs:unsignedInt" minOccurs="0"/>
                                        <xs:element name="cost-amount" type="xs:unsignedInt" minOccurs="1"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="effect-list" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="effect" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="settings-list" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="effect-setting" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:all>
                                                                <xs:element name="setting-name" type="xs:string"
                                                                            minOccurs="1"
                                                                            maxOccurs="1"/>
                                                                <xs:element name="setting-value" type="xs:string"
                                                                            minOccurs="1"
                                                                            maxOccurs="1"/>
                                                            </xs:all>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="target" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="skill-requirements" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="requirement" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="attribute" minOccurs="1" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="TWO_HANDED_CRUSHING_WEAPONS"/>
                                                    <xs:enumeration value="ONE_HANDED_CRUSHING_WEAPONS"/>
                                                    <xs:enumeration value="ONE_HANDED_AXES"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="amount" type="xs:integer" minOccurs="1" maxOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/spell/definition/6.xml
<?xml version="1.0" encoding="UTF-8"?>

<spell:spell xmlns:spell="http://www.swordsandsorcery.com/spell"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://www.swordsandsorcery.com/spell ../schema.xsd">
    <spell:id>6</spell:id>
    <spell:name>Bone spike</spell:name>
    <spell:spell-target>OPPONENT</spell:spell-target>
    <spell:description>
        Deals 1d4 + 4 damage to the opponent. Requires one bone to cast.
    </spell:description>
    <spell:type>DESTRUCTION</spell:type>
    <spell:combat-spell>true</spell:combat-spell>
    <spell:cost-list>
        <spell:cost>
            <spell:cost-type>MANA</spell:cost-type>
            <spell:cost-amount>1</spell:cost-amount>
        </spell:cost>
        <spell:cost>
            <spell:cost-type>ITEM</spell:cost-type>
            <spell:cost-amount>164</spell:cost-amount>
        </spell:cost>
    </spell:cost-list>
    <spell:effect-list>
        <spell:effect target="bone_spike_spell">
            <spell:settings-list>
                <spell:effect-setting>
                    <spell:setting-name>value</spell:setting-name>
                    <spell:setting-value>4</spell:setting-value>
                </spell:effect-setting>
                <spell:effect-setting>
                    <spell:setting-name>d4</spell:setting-name>
                    <spell:setting-value>1</spell:setting-value>
                </spell:effect-setting>
            </spell:settings-list>
        </spell:effect>
    </spell:effect-list>
</spell:spell>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/spell/definition/2.xml
<?xml version="1.0" encoding="UTF-8"?>

<spell:spell xmlns:spell="http://www.swordsandsorcery.com/spell"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://www.swordsandsorcery.com/spell ../schema.xsd">
    <spell:id>2</spell:id>
    <spell:name>Fireball</spell:name>
    <spell:spell-target>OPPONENT</spell:spell-target>
    <spell:description>
        Deals 1d4 + 4 plus the level of your Destruction skill divided by two (this bonus is limited to of five extra damage) to the opponent.
    </spell:description>
    <spell:type>DESTRUCTION</spell:type>
    <spell:combat-spell>true</spell:combat-spell>
    <spell:cost-list>
        <spell:cost>
            <spell:cost-type>MANA</spell:cost-type>
            <spell:cost-amount>3</spell:cost-amount>
        </spell:cost>
    </spell:cost-list>
    <spell:effect-list>
        <spell:effect target="fireball_spell">
            <spell:settings-list>
                <spell:effect-setting>
                    <spell:setting-name>value</spell:setting-name>
                    <spell:setting-value>4</spell:setting-value>
                </spell:effect-setting>
                <spell:effect-setting>
                    <spell:setting-name>d4</spell:setting-name>
                    <spell:setting-value>1</spell:setting-value>
                </spell:effect-setting>
            </spell:settings-list>
        </spell:effect>
    </spell:effect-list>
</spell:spell>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/spell/definition/1.xml
<?xml version="1.0" encoding="UTF-8"?>

<spell:spell xmlns:spell="http://www.swordsandsorcery.com/spell"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://www.swordsandsorcery.com/spell ../schema.xsd">
    <spell:id>1</spell:id>
    <spell:name>Heal</spell:name>
    <spell:type>RESTORATION</spell:type>
    <spell:combat-spell>true</spell:combat-spell>
    <spell:cost-list>
        <spell:cost>
            <spell:cost-type>MANA</spell:cost-type>
            <spell:cost-amount>3</spell:cost-amount>
        </spell:cost>
    </spell:cost-list>
    <spell:effect-list>
        <spell:effect target="com.morethanheroic.swords.combat.domain.effect.entry.HealCombatEffectDefinition">
            <spell:settings-list>
                <spell:effect-setting>
                    <spell:setting-name>amount</spell:setting-name>
                    <spell:setting-value>8</spell:setting-value>
                </spell:effect-setting>
            </spell:settings-list>
        </spell:effect>
    </spell:effect-list>
</spell:spell>
