=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/metadata/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.swordsandsorcery.com/metadata" xmlns="http://www.swordsandsorcery.com/metadata" elementFormDefault="qualified">
    <xs:element name="metadata">
        <xs:complexType>
            <xs:all>
                <xs:element name="id" type="xs:unsignedInt"/>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="values" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="value" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="id" type="xs:unsignedInt"/>
                                        <xs:element name="name" type="xs:string"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/metadata/definition/4.xml
<metadata:metadata xmlns:metadata="http://www.swordsandsorcery.com/metadata"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.swordsandsorcery.com/metadata ../schema.xsd">
    <metadata:id>4</metadata:id>
    <metadata:name>PLAYER_IS_VAMPIRE</metadata:name>
    <metadata:values>
        <metadata:value>
            <metadata:id>0</metadata:id>
            <metadata:name>NOT_VAMPIRE</metadata:name>
        </metadata:value>
        <metadata:value>
            <metadata:id>1</metadata:id>
            <metadata:name>VAMPIRE</metadata:name>
        </metadata:value>
    </metadata:values>
</metadata:metadata>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/metadata/definition/1.xml
<metadata:metadata xmlns:metadata="http://www.swordsandsorcery.com/metadata"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.swordsandsorcery.com/metadata ../schema.xsd">
    <metadata:id>1</metadata:id>
    <metadata:name>PRELUDE_SHOWN</metadata:name>
    <metadata:values>
        <metadata:value>
            <metadata:id>0</metadata:id>
            <metadata:name>NOT_SHOWN</metadata:name>
        </metadata:value>
        <metadata:value>
            <metadata:id>1</metadata:id>
            <metadata:name>ALREADY_SHOWN</metadata:name>
        </metadata:value>
    </metadata:values>
</metadata:metadata>
