=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/map/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.swordsandsorcery.com/map"
           xmlns="http://www.swordsandsorcery.com/map" elementFormDefault="qualified">
    <xs:element name="map">
        <xs:complexType>
            <xs:all>
                <xs:element name="id" type="xs:unsignedInt" minOccurs="1"/>
                <xs:element name="main-shop" type="xs:unsignedInt" minOccurs="1"/>
                <xs:element name="spawn">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="timer" type="xs:unsignedInt" minOccurs="1"/>
                            <xs:element name="alive" type="xs:unsignedInt" minOccurs="1"/>
                            <xs:element name="spawns">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="monster" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:all>
                                                    <xs:element name="id" type="xs:unsignedInt" minOccurs="1"/>
                                                    <xs:element name="chance" type="xs:unsignedInt"/>
                                                    <xs:element name="spots" minOccurs="0">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="spot" minOccurs="1"
                                                                            maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:attribute name="x" type="xs:positiveInteger"
                                                                                      use="required"/>
                                                                        <xs:attribute name="y" type="xs:positiveInteger"
                                                                                      use="required"/>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:all>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="objects">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="object" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="name" type="xs:string" minOccurs="1"/>
                                        <xs:element name="type" minOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="TREE"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:all>
                                    <xs:attribute name="x" type="xs:positiveInteger"
                                                  use="required"/>
                                    <xs:attribute name="y" type="xs:positiveInteger"
                                                  use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/map/definition/1.xml
<?xml version="1.0" encoding="UTF-8"?>

<map:map xmlns:map="http://www.swordsandsorcery.com/map" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.swordsandsorcery.com/map ../schema.xsd">
    <map:id>1</map:id>
    <map:main-shop>1</map:main-shop>
    <map:spawn>
        <map:timer>5</map:timer>
        <!-- respawn in seconds -->
        <map:alive>4000</map:alive>
        <!-- 100 npc can be alive at one time on the map -->
        <map:spawns>
            <map:monster>
                <map:id>1</map:id>
                <map:chance>50</map:chance>
            </map:monster>
            <map:monster>
                <map:id>2</map:id>
                <map:chance>20</map:chance>
            </map:monster>
            <map:monster>
                <map:id>3</map:id>
                <map:chance>15</map:chance>
            </map:monster>
            <map:monster>
                <map:id>4</map:id>
                <map:chance>10</map:chance>
            </map:monster>
            <map:monster>
                <map:id>5</map:id>
                <map:chance>5</map:chance>
            </map:monster>
        </map:spawns>
    </map:spawn>
    <map:objects>
        <map:object x="111" y="22">
            <map:name>Mapple tree</map:name>
            <map:type>TREE</map:type>
        </map:object>
        <map:object x="11" y="22">
            <map:name>Oak tree</map:name>
            <map:type>TREE</map:type>
        </map:object>
    </map:objects>
</map:map>
