=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/loot/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.swordsandsorcery.com/loot"
           xmlns="http://www.swordsandsorcery.com/loot" elementFormDefault="qualified">
    <xs:element name="loot">
        <xs:complexType>
            <xs:all>
                <xs:element name="droplist">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="drop" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="item" type="xs:unsignedInt" minOccurs="1"/>
                                        <xs:element name="amount" minOccurs="1">
                                            <xs:complexType>
                                                <xs:all>
                                                    <xs:element name="min" type="xs:unsignedInt" minOccurs="0"/>
                                                    <xs:element name="max" type="xs:unsignedInt" minOccurs="1"/>
                                                </xs:all>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="chance" type="xs:double" minOccurs="1"/>
                                        <xs:element name="identified" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/loot/definition/9.xml
<?xml version="1.0" encoding="UTF-8"?>

<loot:loot xmlns:loot="http://www.swordsandsorcery.com/loot"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.swordsandsorcery.com/loot ../schema.xsd">
    <loot:id>9</loot:id>
    <loot:droplist>
        <loot:drop>
            <loot:item>213</loot:item>
            <loot:amount>
                <loot:max>1</loot:max>
            </loot:amount>
            <loot:chance>3</loot:chance>
            <loot:identified>false</loot:identified>
        </loot:drop>
        <loot:drop>
            <loot:item>208</loot:item>
            <loot:amount>
                <loot:max>1</loot:max>
            </loot:amount>
            <loot:chance>0.5</loot:chance>
            <loot:identified>false</loot:identified>
        </loot:drop>
        <loot:drop>
            <loot:item>207</loot:item>
            <loot:amount>
                <loot:min>1</loot:min>
                <loot:max>2</loot:max>
            </loot:amount>
            <loot:chance>3</loot:chance>
            <loot:identified>false</loot:identified>
        </loot:drop>
        <loot:drop>
            <loot:item>210</loot:item>
            <loot:amount>
                <loot:min>1</loot:min>
                <loot:max>3</loot:max>
            </loot:amount>
            <loot:chance>6</loot:chance>
        </loot:drop>
        <loot:drop>
            <loot:item>211</loot:item>
            <loot:amount>
                <loot:max>1</loot:max>
            </loot:amount>
            <loot:chance>1</loot:chance>
        </loot:drop>
        <loot:drop>
            <loot:item>205</loot:item>
            <loot:amount>
                <loot:max>1</loot:max>
            </loot:amount>
            <loot:chance>3</loot:chance>
        </loot:drop>
        <loot:drop>
            <loot:item>203</loot:item>
            <loot:amount>
                <loot:min>1</loot:min>
                <loot:max>4</loot:max>
            </loot:amount>
            <loot:chance>100</loot:chance>
        </loot:drop>
        <loot:drop>
            <loot:item>202</loot:item>
            <loot:amount>
                <loot:max>1</loot:max>
            </loot:amount>
            <loot:chance>2</loot:chance>
        </loot:drop>
        <loot:drop>
            <loot:item>191</loot:item>
            <loot:amount>
                <loot:max>1</loot:max>
            </loot:amount>
            <loot:chance>2</loot:chance>
        </loot:drop>
        <loot:drop>
            <loot:item>188</loot:item>
            <loot:amount>
                <loot:max>1</loot:max>
            </loot:amount>
            <loot:chance>2</loot:chance>
        </loot:drop>
        <loot:drop>
            <loot:item>186</loot:item>
            <loot:amount>
                <loot:max>1</loot:max>
            </loot:amount>
            <loot:chance>2</loot:chance>
        </loot:drop>
        <loot:drop>
            <loot:item>189</loot:item>
            <loot:amount>
                <loot:min>1</loot:min>
                <loot:max>3</loot:max>
            </loot:amount>
            <loot:chance>5</loot:chance>
        </loot:drop>
        <loot:drop>
            <loot:item>165</loot:item>
            <loot:amount>
                <loot:min>1</loot:min>
                <loot:max>2</loot:max>
            </loot:amount>
            <loot:chance>5</loot:chance>
        </loot:drop>
    </loot:droplist>
</loot:loot>
