=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/recipe/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.swordsandsorcery.com/recipe"
           xmlns="http://www.swordsandsorcery.com/recipe" elementFormDefault="qualified">
    <xs:element name="recipe">
        <xs:complexType>
            <xs:all>
                <xs:element name="id" type="xs:unsignedInt"/>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="type">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="COOKING"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="chance">
                    <xs:simpleType>
                        <xs:restriction base="xs:unsignedInt">
                            <xs:minInclusive value="0"/>
                            <xs:maxInclusive value="100"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="ingredient-list">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ingredient" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="id" type="xs:unsignedInt"/>
                                        <xs:element name="amount" type="xs:unsignedInt"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="reward-list">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="reward" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="id" type="xs:unsignedInt"/>
                                        <xs:element name="amount" type="xs:unsignedInt"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="experience-list">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="experience" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="skill">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="COOKING"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="amount" type="xs:unsignedInt"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="requirement-list">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="requirement" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="skill">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="COOKING"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="amount" type="xs:unsignedInt"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/recipe/definition/15.xml
<?xml version="1.0" encoding="UTF-8"?>

<recipe:recipe xmlns:recipe="http://www.swordsandsorcery.com/recipe" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.swordsandsorcery.com/recipe ../schema.xsd">
    <recipe:id>15</recipe:id>
    <recipe:name>Wolf skin (cured)</recipe:name>
    <recipe:type>LEATHERWORKING_CURING</recipe:type>
    <recipe:chance>100</recipe:chance>
    <recipe:requirement-list>
        <recipe:skill-requirement>
            <recipe:skill>LEATHERWORKING</recipe:skill>
            <recipe:amount>5</recipe:amount>
        </recipe:skill-requirement>
    </recipe:requirement-list>
    <recipe:ingredient-list>
        <recipe:ingredient>
            <recipe:id>70</recipe:id>
            <recipe:amount>1</recipe:amount>
        </recipe:ingredient>
        <recipe:ingredient>
            <recipe:id>75</recipe:id>
            <recipe:amount>1</recipe:amount>
        </recipe:ingredient>
    </recipe:ingredient-list>
    <recipe:reward-list>
        <recipe:reward>
            <recipe:id>16</recipe:id>
            <recipe:amount>1</recipe:amount>
        </recipe:reward>
    </recipe:reward-list>
    <recipe:experience-list>
        <recipe:experience>
            <recipe:skill>LEATHERWORKING</recipe:skill>
            <recipe:amount>35</recipe:amount>
        </recipe:experience>
    </recipe:experience-list>
</recipe:recipe>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/recipe/definition/2.xml
<?xml version="1.0" encoding="UTF-8"?>

<recipe:recipe xmlns:recipe="http://www.swordsandsorcery.com/recipe" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.swordsandsorcery.com/recipe ../schema.xsd">
    <recipe:id>2</recipe:id>
    <recipe:name>Peanut butter</recipe:name>
    <recipe:type>COOKING</recipe:type>
    <recipe:chance>100</recipe:chance>
    <recipe:requirement-list>
        <recipe:requirement>
            <recipe:skill>COOKING</recipe:skill>
            <recipe:amount>3</recipe:amount>
        </recipe:requirement>
      <!-- Need to add Pestle and Mortar as a requirement! -->
    </recipe:requirement-list>
    <recipe:ingredient-list>
        <recipe:ingredient>
            <recipe:id>58</recipe:id>
            <recipe:amount>1</recipe:amount>
        </recipe:ingredient>
        <recipe:ingredient>
            <recipe:id>56</recipe:id>
            <recipe:amount>1</recipe:amount>
        </recipe:ingredient>
    </recipe:ingredient-list>
    <recipe:reward-list>
        <recipe:reward>
            <recipe:id>59</recipe:id>
            <recipe:amount>1</recipe:amount>
        </recipe:reward>
    </recipe:reward-list>
    <recipe:experience-list>
        <recipe:experience>
            <recipe:skill>COOKING</recipe:skill>
            <recipe:amount>15</recipe:amount>
        </recipe:experience>
    </recipe:experience-list>
</recipe:recipe>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/recipe/definition/75.xml
<?xml version="1.0" encoding="UTF-8"?>

<recipe:recipe xmlns:recipe="http://www.swordsandsorcery.com/recipe"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.swordsandsorcery.com/recipe ../schema.xsd">
    <recipe:id>75</recipe:id>
    <recipe:name>Robinia Staff</recipe:name>
    <recipe:type>IMBUING</recipe:type>
    <recipe:chance>100</recipe:chance>
    <recipe:requirement-list>
        <recipe:skill-requirement>
            <recipe:skill>IMBUING</recipe:skill>
            <recipe:amount>1</recipe:amount>
        </recipe:skill-requirement>
        <recipe:resource-requirement>
            <recipe:resource>MANA</recipe:resource>
            <recipe:amount>8</recipe:amount>
        </recipe:resource-requirement>
    </recipe:requirement-list>
    <recipe:ingredient-list>
        <recipe:ingredient>
            <recipe:id>231</recipe:id>
            <recipe:amount>1</recipe:amount>
        </recipe:ingredient>
    </recipe:ingredient-list>
    <recipe:reward-list>
        <recipe:reward>
            <recipe:id>36</recipe:id>
            <recipe:amount>1</recipe:amount>
        </recipe:reward>
    </recipe:reward-list>
    <recipe:experience-list>
        <recipe:experience>
            <recipe:skill>IMBUING</recipe:skill>
            <recipe:amount>40</recipe:amount>
        </recipe:experience>
    </recipe:experience-list>
</recipe:recipe>

=== daggers-and-sorcery/daggers-and-sorcery-datapack/src/main/resources/data/recipe/definition/74.xml
<?xml version="1.0" encoding="UTF-8"?>

<recipe:recipe xmlns:recipe="http://www.swordsandsorcery.com/recipe" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.swordsandsorcery.com/recipe ../schema.xsd">
    <recipe:id>74</recipe:id>
    <recipe:name>Bloodlord's Pride</recipe:name>
    <recipe:type>SMITHING</recipe:type>
    <recipe:chance>100</recipe:chance>
    <recipe:requirement-list>
        <recipe:skill-requirement>
            <recipe:skill>SMITHING</recipe:skill>
            <recipe:amount>15</recipe:amount>
        </recipe:skill-requirement>
        <recipe:item-requirement>
            <recipe:id>8</recipe:id>
            <recipe:amount>1</recipe:amount>
        </recipe:item-requirement>
    </recipe:requirement-list>
    <recipe:ingredient-list>
        <recipe:ingredient>
            <recipe:id>5</recipe:id>
            <recipe:amount>16</recipe:amount>
        </recipe:ingredient>
        <recipe:ingredient>
            <recipe:id>212</recipe:id>
            <recipe:amount>1</recipe:amount>
        </recipe:ingredient>
        <recipe:ingredient>
            <recipe:id>116</recipe:id>
            <recipe:amount>1</recipe:amount>
        </recipe:ingredient>
    </recipe:ingredient-list>
    <recipe:reward-list>
        <recipe:reward>
            <recipe:id>230</recipe:id>
            <recipe:amount>1</recipe:amount>
        </recipe:reward>
    </recipe:reward-list>
    <recipe:experience-list>
        <recipe:experience>
            <recipe:skill>SMITHING</recipe:skill>
            <recipe:amount>250</recipe:amount>
        </recipe:experience>
    </recipe:experience-list>
</recipe:recipe>
